# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tg_dist_ind <- function(x, a, b) {
    .Call(`_HW4MC_tg_dist_ind`, x, a, b)
}

tg_dist <- function(x, a, b) {
    .Call(`_HW4MC_tg_dist`, x, a, b)
}

isRcpp <- function(n, a, b, df) {
    .Call(`_HW4MC_isRcpp`, n, a, b, df)
}

rsRcpp <- function(n, alp, a, b, df) {
    .Call(`_HW4MC_rsRcpp`, n, alp, a, b, df)
}

